baseURL = "https://markushartmann.dev/"
languageCode = "de-de"
title = "Markus Hartmann"
paginate = 5
theme = "hugo-clarity"

[params]
twitter = "@_markushartmann"
mobileNavigation = "right"
numberOfRecentPosts = 5
numberOfFeaturedPosts = 3
env = "production"
title = "Markus Hartmann"
description = ";-)"
author = "Markus Hartmann"

enableRobotsTXT= true
buildDrafts= false
buildFuture= false
buildExpored= false

[minify]
disableXML = true
minifyOutput= true