baseURL = "https://markushartmann.dev/"
languageCode = "de-de"
title = "Markus Hartmann"
theme = "axiom"

paginate = 2
canonifyURLs = false
summaryLength = 40
rssLimit = 100
enableEmoji = true
enableRobotsTXT = true
pluralizelisttitles = false

[minify]
disableXML = true
minifyOutput= true

[permalinks]
posts = "/:filename"

[params]
mainSections = ["posts"]
copyrightYear = 2020
# Go Reference time: Mon Jan 2 15:04:05 MST 2006
dateFormat = "Jan 2, 2006 3:04PM"
highlight = "dark"

[params.brand]
domain = "markushartmann.dev"
email = "info@markushartmann.dev"

[params.social]
github = "https://github.com/aidun"
linkedin = "https://www.linkedin.com/in/markush1986"
twitter = "https://twitter.com/_markushartmann"
footer = ["twitter", "github", "linkedin"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = false
footnote = true
linkify = false
strikethrough = false
table = true
taskList = false
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
attribute = false
[markup.highlight]
codeFences = true
noClasses = false
tabWidth = 2

[menu]
[[menu.main]]
url = "/posts/"
name = "Posts"
weight = 1
[[menu.main]]
url = "/posts/"
name = "Posts"
weight = 2
[[menu.main]]
url = "/about/"
name = "About"
weight = 3
[[menu.main]]
url = "/contact/"
name = "Contact"
weight = 4
[[menu.foot]]
url = "/privacy/"
name = "Privacy"
weight = 1